// AUTO-DERIVED from Sample.xlsx (QA audit export). Two programs
// (External / Internal) x six dispositions, each a weighted parameter set.
// Weights renormalized to sum 1.0 per disposition. criticalType inferred by
// keyword; PEWC is a compliance auto-fail (weight 0, pass/fail).
import type { CriticalType } from '@awr/shared';

export type Program = 'External' | 'Internal';
export interface FormParam { text: string; weight: number; criticalType: CriticalType; autoFail: boolean; }
export interface CoachingForm { program: Program; disposition: string; params: FormParam[]; }

export const COACHING_FORMS: CoachingForm[] = [
  { program: "External", disposition: "Claim-Service Appointment", params: [
    { text: "Did the agent verify the caller's first and last name?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent listen actively, ask clarifying questions, and acknowledge the customer's reason for calling?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent enter the customer's information correctly?", weight: 0.0488, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent meet the customer's need by providing complete and accurate information?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent take full ownership of the customer's issue by clearly explaining the next steps?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent demonstrate a professional, reassuring, and business friendly tone?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent build rapport and/or provide empathy when appropriate?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent properly close the call by thanking the customer for calling?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent properly close the call by confirming the customer's satisfaction?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent mention the post-call survey?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.0244, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.0244, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.0244, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent follow the probing questions in Salesforce", weight: 0.0976, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintain a professional tone and deliver required disclosure", weight: 0.0244, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent set up the claim correctly, including the correct provider", weight: 0.0976, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent escalate the customer's issue to a supervisor if the customer requested one? Did the agent Follow Proper Hold Procedures", weight: 0.0732, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent offer an upsell after the issue was properly resolved", weight: 0.0244, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintained control of the call and the call flow?", weight: 0.0732, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent recap all actions that took place during the call", weight: 0.0244, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.0244, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.0, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: -0.0004, criticalType: "CUSTOMER", autoFail: false },
  ] },
  { program: "External", disposition: "Billing and Payment", params: [
    { text: "Did the agent verify the caller's first and last name?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent listen actively, ask clarifying questions, and acknowledge the customer's reason for calling?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent enter the customer's information correctly?", weight: 0.1, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent meet the customer's need by providing complete and accurate information?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent take full ownership of the customer's issue by clearly explaining the next steps?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent demonstrate a professional, reassuring, and business friendly tone?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent build rapport and/or provide empathy when appropriate?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent properly close the call by thanking the customer for calling?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent properly close the call by confirming the customer's satisfaction?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent mention the post-call survey?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
  ] },
  { program: "External", disposition: "Claim", params: [
    { text: "Did the agent verify the caller's first and last name?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent listen actively, ask clarifying questions, and acknowledge the customer's reason for calling?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent enter the customer's information correctly?", weight: 0.1, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent meet the customer's need by providing complete and accurate information?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent take full ownership of the customer's issue by clearly explaining the next steps?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent demonstrate a professional, reassuring, and business friendly tone?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent build rapport and/or provide empathy when appropriate?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent properly close the call by thanking the customer for calling?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent properly close the call by confirming the customer's satisfaction?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent mention the post-call survey?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
  ] },
  { program: "External", disposition: "Eligibility and Benefit", params: [
    { text: "Did the agent verify the caller's first and last name?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent listen actively, ask clarifying questions, and acknowledge the customer's reason for calling?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent enter the customer's information correctly?", weight: 0.1, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent meet the customer's need by providing complete and accurate information?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent take full ownership of the customer's issue by clearly explaining the next steps?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent demonstrate a professional, reassuring, and business friendly tone?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent build rapport and/or provide empathy when appropriate?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent properly close the call by thanking the customer for calling?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent properly close the call by confirming the customer's satisfaction?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent mention the post-call survey?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
  ] },
  { program: "External", disposition: "Transfer to Retention (Cancellation)", params: [
    { text: "Did the agent verify the caller's first and last name?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent listen actively, ask clarifying questions, and acknowledge the customer's reason for calling?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent enter the customer's information correctly?", weight: 0.0488, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent meet the customer's need by providing complete and accurate information?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent take full ownership of the customer's issue by clearly explaining the next steps?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent demonstrate a professional, reassuring, and business friendly tone?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent build rapport and/or provide empathy when appropriate?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent properly close the call by thanking the customer for calling?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent properly close the call by confirming the customer's satisfaction?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent mention the post-call survey?", weight: 0.0488, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.0244, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent greet the customer warmly, introduce themselves, and introduce the company?", weight: 0.0244, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.0244, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs?", weight: 0.0976, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent present the key benefits of the program(s)?", weight: 0.0976, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent professionally handle objections and use approved rebuttals?", weight: 0.0732, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent finalize the call outcome (save or cancel), recap the details of the call, and offer additional assistance? Did the agent document the call accurately in the Notes section? Did the agent provide all the required disclosures?", weight: 0.0976, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent maintain a professional tone?", weight: 0.0728, criticalType: "CUSTOMER", autoFail: false },
  ] },
  { program: "External", disposition: "Reimbursement", params: [
    { text: "Did the agent verify the caller's first and last name?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent listen actively, ask clarifying questions, and acknowledge the customer's reason for calling?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent enter the customer's information correctly?", weight: 0.1, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent meet the customer's need by providing complete and accurate information?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent take full ownership of the customer's issue by clearly explaining the next steps?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent demonstrate a professional, reassuring, and business friendly tone?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent build rapport and/or provide empathy when appropriate?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the Agent properly close the call by thanking the customer for calling?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent properly close the call by confirming the customer's satisfaction?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent mention the post-call survey?", weight: 0.1, criticalType: "CUSTOMER", autoFail: false },
  ] },
  { program: "Internal", disposition: "Eligibility and Benefit", params: [
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.0244, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.0244, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.0244, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent follow the probing questions in Salesforce", weight: 0.0976, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintain a professional tone and deliver required disclosure", weight: 0.0244, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent set up the claim correctly, including the correct provider", weight: 0.0976, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent escalate the customer's issue to a supervisor if the customer requested one? Did the agent Follow Proper Hold Procedures", weight: 0.0732, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent offer an upsell after the issue was properly resolved", weight: 0.0244, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintained control of the call and the call flow?", weight: 0.0732, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent recap all actions that took place during the call", weight: 0.0244, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.0244, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.0732, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.0732, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent follow the approved upsell cadence and offer TLS/TLP first", weight: 0.0976, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent lead with ACH as the primary payment method before offering alternatives", weight: 0.0732, criticalType: "BUSINESS", autoFail: false },
    { text: "Was the offer clearly presented with key benefits and customer alignment", weight: 0.0732, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent handle objections confidently and use approved rebuttals", weight: 0.0488, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent ask for the sale and clearly confirm the enrollment details", weight: 0.0244, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintain a professional tone and deliver required disclosures", weight: 0.0244, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent follow the correct product cadence for new customers", weight: 0.0, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent personalize the offer based on customer\u2019s current bill and coverage profile", weight: 0.0, criticalType: "BUSINESS", autoFail: false },
    { text: "PEWC  (Prior Express Written Consent)", weight: -0.0004, criticalType: "COMPLIANCE", autoFail: true },
  ] },
  { program: "Internal", disposition: "Claim-Service Appointment", params: [
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.037, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.037, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent follow the probing questions in Salesforce", weight: 0.1481, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintain a professional tone and deliver required disclosure", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent set up the claim correctly, including the correct provider", weight: 0.1481, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent escalate the customer's issue to a supervisor if the customer requested one? Did the agent Follow Proper Hold Procedures", weight: 0.1111, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent offer an upsell after the issue was properly resolved", weight: 0.037, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintained control of the call and the call flow?", weight: 0.1111, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent recap all actions that took place during the call", weight: 0.037, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.1111, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.1115, criticalType: "CUSTOMER", autoFail: false },
  ] },
  { program: "Internal", disposition: "Billing and Payment", params: [
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.037, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.037, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent follow the probing questions in Salesforce", weight: 0.1481, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintain a professional tone and deliver required disclosure", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent set up the claim correctly, including the correct provider", weight: 0.1481, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent escalate the customer's issue to a supervisor if the customer requested one? Did the agent Follow Proper Hold Procedures", weight: 0.1111, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent offer an upsell after the issue was properly resolved", weight: 0.037, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintained control of the call and the call flow?", weight: 0.1111, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent recap all actions that took place during the call", weight: 0.037, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.1111, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.1115, criticalType: "CUSTOMER", autoFail: false },
  ] },
  { program: "Internal", disposition: "Claim", params: [
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.037, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.037, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent follow the probing questions in Salesforce", weight: 0.1481, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintain a professional tone and deliver required disclosure", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent set up the claim correctly, including the correct provider", weight: 0.1481, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent escalate the customer's issue to a supervisor if the customer requested one? Did the agent Follow Proper Hold Procedures", weight: 0.1111, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent offer an upsell after the issue was properly resolved", weight: 0.037, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintained control of the call and the call flow?", weight: 0.1111, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent recap all actions that took place during the call", weight: 0.037, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.1111, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.1115, criticalType: "CUSTOMER", autoFail: false },
  ] },
  { program: "Internal", disposition: "Transfer to Retention (Cancellation)", params: [
    { text: "Did the agent follow the proper account authentication process?", weight: 0.0476, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent greet the customer warmly, introduce themselves, and introduce the company?", weight: 0.0476, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.0476, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs?", weight: 0.1905, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent present the key benefits of the program(s)?", weight: 0.1905, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent professionally handle objections and use approved rebuttals?", weight: 0.1429, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent finalize the call outcome (save or cancel), recap the details of the call, and offer additional assistance? Did the agent document the call accurately in the Notes section? Did the agent provide all the required disclosures?", weight: 0.1905, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent maintain a professional tone?", weight: 0.1428, criticalType: "CUSTOMER", autoFail: false },
  ] },
  { program: "Internal", disposition: "Reimbursement", params: [
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.037, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.037, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent follow the probing questions in Salesforce", weight: 0.1481, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintain a professional tone and deliver required disclosure", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent set up the claim correctly, including the correct provider", weight: 0.1481, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent escalate the customer's issue to a supervisor if the customer requested one? Did the agent Follow Proper Hold Procedures", weight: 0.1111, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent offer an upsell after the issue was properly resolved", weight: 0.037, criticalType: "BUSINESS", autoFail: false },
    { text: "Did the agent maintained control of the call and the call flow?", weight: 0.1111, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent recap all actions that took place during the call", weight: 0.037, criticalType: "PROCESS", autoFail: false },
    { text: "Did the agent follow the proper account authentication process?", weight: 0.037, criticalType: "COMPLIANCE", autoFail: false },
    { text: "Did the agent greet the customer warmly, introduce themselves and the company", weight: 0.1111, criticalType: "CUSTOMER", autoFail: false },
    { text: "Did the agent ask questions to understand the reason for the call and any additional needs", weight: 0.1115, criticalType: "CUSTOMER", autoFail: false },
  ] },
];

export const DISPOSITIONS = Array.from(new Set(COACHING_FORMS.map((f) => f.disposition)));
export function findForm(program: Program, disposition: string): CoachingForm | undefined {
  return COACHING_FORMS.find((f) => f.program === program && f.disposition === disposition)
    ?? COACHING_FORMS.find((f) => f.disposition === disposition);
}
